"""added_email_password_3

Revision ID: 41cb2ce1f6bf
Revises: 809eadfa6c19
Create Date: 2024-09-22 18:56:06.183590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41cb2ce1f6bf'
down_revision: Union[str, None] = '809eadfa6c19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_register', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users_register', 'password',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_register', 'password',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users_register', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_table('user_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('access_key', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('refresh_key', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_tokens_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_tokens_pkey')
    )
    op.create_index('ix_user_tokens_refresh_key', 'user_tokens', ['refresh_key'], unique=False)
    op.create_index('ix_user_tokens_access_key', 'user_tokens', ['access_key'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    # ### end Alembic commands ###
